-- Embalaje · Arqueta Folding — esquema y catálogo inicial para Supabase.
-- Ejecutar UNA VEZ en el SQL Editor de Supabase (pestaña SQL → New query → Run).
-- Vuelve a ejecutarlo solo si quieres empezar de cero: borra y recrea todo.

drop table if exists truck_loads cascade;
drop table if exists products cascade;
drop table if exists clients cascade;
drop table if exists destinations cascade;
drop table if exists trucks cascade;

create table clients (
  id          bigint generated by default as identity primary key,
  name        text not null
);

create table products (
  id                  bigint generated by default as identity primary key,
  name                text not null,
  sku                 text,
  client_id           bigint references clients(id) on delete set null,
  boxes_per_corrugado integer,
  cantidad_por_cama   integer,
  estiba              integer,
  unit_price          numeric
);
create index on products (client_id);

create table trucks (
  id               bigint generated by default as identity primary key,
  name             text not null,
  pallet_capacity  integer not null,
  freight_category text
);

create table destinations (
  id              bigint generated by default as identity primary key,
  name            text not null,
  cost_trailer    numeric,
  cost_torton     numeric,
  cost_camion_35  numeric,
  cost_reparto    numeric
);

create table truck_loads (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz not null default now(),
  name             text,
  truck_id         bigint,
  truck_name       text,
  pallet_capacity  integer,
  status           text not null default 'planificando',
  pallets_used     integer,
  destination_id   bigint,
  destination_name text,
  freight_cost     numeric,
  items            jsonb not null default '[]'::jsonb
);
create index on truck_loads (created_at desc);


-- ===== catálogo inicial =====
insert into clients (id, name) values
  (121, 'ARAM LUZ'),
  (95, 'ARAMO'),
  (97, 'AVERY'),
  (125, 'BIMFASA'),
  (129, 'BOXIFY'),
  (120, 'CASA LUMBRE'),
  (117, 'CHOCOLATERA NAYARIT'),
  (114, 'CODIGO FOODS'),
  (128, 'CUETARA'),
  (133, 'CUISINOS ARTESANOS QUESEROS'),
  (123, 'DESTILERIA SANTA LUCIA'),
  (107, 'DIBIDIDA'),
  (122, 'FREELIFE'),
  (137, 'FREIXENET'),
  (119, 'FRUITEX DE MEXICO'),
  (106, 'FULLER'),
  (113, 'GALLETERA KUKI'),
  (126, 'GLASSIA'),
  (98, 'GO2 PARTNERS'),
  (118, 'GRAND MAYAN'),
  (116, 'GREAT VALUE'),
  (136, 'GRUPO SALAVERRIA'),
  (99, 'HOT_LINKS'),
  (102, 'KLASSCO'),
  (130, 'KORES'),
  (124, 'LA CETTO'),
  (108, 'LA ITALIANA'),
  (138, 'LA MADRILEÑA'),
  (132, 'LA MALLORQUINA'),
  (134, 'LABORATORIOS SERRAL'),
  (110, 'LALA'),
  (115, 'LASTUR'),
  (112, 'LEON'),
  (109, 'LICORERA DEL SUR'),
  (135, 'MACMA'),
  (127, 'MEDIX'),
  (100, 'PREMIUM BEERS GROUP'),
  (105, 'PRIMO'),
  (94, 'SALUTARE'),
  (103, 'SAYOSHI'),
  (101, 'TAIFELDS'),
  (111, 'TEQUILERA DE ARANDAS'),
  (131, 'TORI TORI'),
  (93, 'VENUS CUP SA DE CV'),
  (96, 'VITRALITO'),
  (104, 'WORLD CONVERTING SOLUTIONS');

insert into products (id, name, sku, client_id, boxes_per_corrugado, cantidad_por_cama, estiba, unit_price) values
  (494, 'CAJA PARA VELADORAS 3X3', 'AFFP0098', 121, 50, 6, 3, null),
  (495, 'INSERTO CAJA PARA VELADORAS 3X3', 'AFFP0099', 121, 660, 8, 4, null),
  (416, 'BASE_ATAUD', 'AFFP0021', 95, 500, 4, 4, null),
  (404, 'REFACCION_13', 'AFFP0009', 95, 220, 9, 4, null),
  (403, 'REFACCION_18', 'AFFP0008', 95, 160, 9, 4, null),
  (401, 'REFACCION_4', 'AFFP0006', 95, 160, 9, 4, null),
  (402, 'REFACCIÓN_5', 'AFFP0007', 95, 160, 9, 4, null),
  (415, 'TAPA_ATAUD', 'AFFP0020', 95, 440, 9, 5, null),
  (409, 'SOBRE FOLDER', 'AFFP0014', 97, 400, 3, 7, null),
  (516, 'DISPLAY FRUIT SNACK 10 CT - SAVE A LOT', 'AFFP0119', 125, 252, 6, 5, null),
  (514, 'DISPLAY SOLLEY PIECES 12PC', 'AFFP0117', 125, 200, 9, 5, null),
  (517, 'FRUIT JERKY 16 CT COSTCO', 'AFFP0120', 125, null, null, null, null),
  (518, 'GUMMIES 5 CT ATM', 'AFFP0121', 125, null, null, null, null),
  (565, 'INSERTO FAJILLA CHAROLA GRANDE TORI TORI', 'AFFP0171', 125, 744, 8, 4, null),
  (530, 'JERKY 12 CT ATM', 'AFFP0134', 125, 360, 6, 5, null),
  (528, 'JERKY 14 CT ATM', 'AFFP0132', 125, 312, 6, 5, null),
  (560, 'JERKY 14 CT ATM NVO', 'AFFP0166', 125, 120, 5, 6, null),
  (531, 'JERKY_5CT_ATM', 'AFFP0135', 125, 150, 8, 4, null),
  (529, 'JERKY_5CT_ATM', 'AFFP0133', 125, 528, 8, 4, null),
  (575, 'REJILLA CUBO PT 1', 'AFFP0181', 125, 130, 6, 5, null),
  (574, 'REJILLA_CUBO_PT2', 'AFFP0180', 125, 200, 5, 6, null),
  (519, 'SOLELY FRUIT JERKY 12CT ATM', 'AFFP0123', 125, 520, 5, 6, null),
  (520, 'SOLELY FRUIT JERKY 16 CT ATM', 'AFFP0124', 125, 50, 9, 6, null),
  (506, 'SOLELY GUMMIES 5 - 0.7 OZ', 'AFFP0109', 125, 520, 6, 5, null),
  (527, 'SOLELY GUMMIES 5 CT', 'AFFP0131', 125, 352, 9, 5, null),
  (505, 'SOLELY ORGANIC 12 PZS', 'AFFP0108', 125, 400, 8, 4, null),
  (526, 'SOLELY_GUMMIES_10CT_ATM', 'AFFP0130', 125, 348, 8, 4, null),
  (557, 'CAJA RELOJ KNOCK OUT (BASE)', 'AFFP0163', 129, 260, 6, 5, null),
  (559, 'CAJA RELOJ KNOCK OUT (INSERTO)', 'AFFP0165', 129, 957, 9, 5, null),
  (558, 'CAJA RELOJ KNOCK OUT (TAPA)', 'AFFP0164', 129, 380, 6, 5, null),
  (540, 'COMFY FOODS', 'AFFP0144', 129, 75, 5, 6, null),
  (553, 'IMPRESION DE CAJAS DISPLAY SHOPX', 'AFFP0159', 129, 175, 8, 4, null),
  (554, 'INSERTO IMPRESION DE CAJAS DISPLAY SHOPX', 'AFFP0160', 129, 390, 9, 5, null),
  (492, 'VMC_PALOMA_4PACK_GALLO', 'AFFP0096', 120, 282, 6, 8, null),
  (490, 'BICARBONATO 1KG', 'AFFP0094', 117, 380, 5, 6, null),
  (588, 'BICARBONATO 500 GRMS', 'AFFP0194', 117, 320, 6, 5, null),
  (475, 'BICARBONATO DE SODIO 227G', 'AFFP0079', 117, 1040, 8, 4, null),
  (536, 'COLORANTE_ROJO_VALLEY_FOODS', 'AFFP0140', 117, 2352, 5, 6, null),
  (473, 'COOKIES CHRISTMAS', 'AFFP0077', 117, 725, 6, 5, null),
  (476, 'GV_CASITA_JENGIBRE_170G', 'AFFP0080', 117, 325, 5, 5, null),
  (478, 'GV_CASITA_JENGIBRE_795G.', 'AFFP0082', 117, 125, 5, 5, null),
  (477, 'GV_MUÑECO_JENGIBRE_652G.', 'AFFP0081', 117, 150, 6, 5, null),
  (539, 'ME 0379 CAJITA EXTRACTO NARANJA VALLEY FOODS 59ML', 'AFFP0143', 117, 858, 9, 5, null),
  (537, 'ME 0384 EXHIBIDOR EXTRACTOS VALLEY FOODS', 'AFFP0141', 117, 150, 9, 5, null),
  (538, 'ME 0385 EXHIBIDOR COLORANTES 29ML VALLEY FOODS', 'AFFP0142', 117, 180, 9, 5, null),
  (580, 'ME 0387 EXHIBIDOR GRANDE AZUCAR Y SPRINKLE VALLEY FOODS', 'AFFP0186', 117, 120, 5, 6, null),
  (581, 'ME0386 EXHIBIDOR BOTE CHICO PERLAS VALLEY FOODS', 'AFFP0187', 117, 120, 9, 5, null),
  (569, 'ME0510_CAJITA_KIT_COOKIE_DECORATION_MONO_GEMELO', 'AFFP0175', 117, 475, 6, 5, null),
  (493, 'MEGA CASITA DE GALLETA 396 GR', 'AFFP0097', 117, 200, 9, 5, null),
  (512, 'PEARLS BOTE CHICO', 'AFFP0115', 117, 110, 9, 5, null),
  (513, 'PEARLS BOTE GRANDE', 'AFFP0116', 117, 168, 6, 3, null),
  (472, 'CAJA CROISSANT DEDAL', 'AFFP0076', 114, 175, 6, 4, null),
  (463, 'CAJA_CROISSANT_5PACK', 'AFFP0068', 114, 140, 9, 5, null),
  (464, 'CAJILLA_MINI_CIABATTA (3 CAMBIOS)', 'AFFP0068', 114, 120, 9, 5, null),
  (458, 'CHICKEN BAKE 4 PZAS', 'AFFP0063', 114, 125, 9, 5, null),
  (534, 'GALLETAS NAPOLITANAS', 'AFFP0138', 128, 180, 8, 5, null),
  (556, 'CAJA QUESO CREMA', 'AFFP0162', 133, 160, 9, 5, null),
  (522, 'CAJA ESTUCHE EL DESTILADOR ARTESANAL BLANCO REPOSADO Y AÑEJO 375ML 3PACK (CAJA)', 'AFFP0126', 123, 39, 6, 3, null),
  (502, 'DUO PACK DESTILADOR', 'AFFP0105', 123, 65, 6, 3, null),
  (521, 'ESTUCHE REFORZADO EL DESTILADOR AÑEJO CRISTALINO 750ML', 'AFFP0125', 123, 40, 9, 5, null),
  (550, 'ESTUCHE TIERRA AZTECA 100%BLANCO 3 PACK 375ML', 'AFFP0156', 123, 70, 6, 3, null),
  (551, 'INSERTO 1 ESTUCHE TIERRA AZTECA 100 BLANCO 3 PACK 375ML', 'AFFP0157', 123, 570, 5, 6, null),
  (552, 'INSERTO 2 ESTUCHE TIERRA AZTECA 100 BLANCO 3 PACK 375ML', 'AFFP0158', 123, 360, 5, 6, null),
  (507, 'INSERTO EL DESTILADOR BLANCO DUO PACK 700ML', 'AFFP0110', 123, 2250, 9, 5, null),
  (523, 'INSERTO ESTUCHE EL DESTILADOR ARTESANAL BLANCO REPOSADO Y AÑEJO 375ML 3PACK (INSERTO)', 'AFFP0127', 123, 2084, 20, 8, null),
  (500, 'TEQUILA TIERRA AZTECA', 'AFFP0104', 123, 50, 5, 6, null),
  (440, 'SELECTO STEVIA 300', 'AFFP0045', 107, 180, 9, 5, null),
  (496, '10 PACK MINI', 'AFFP0100', 122, 80, 6, 3, null),
  (589, 'ESTUCHE FREIXENET CON COPA/MUESTRA', null, 137, null, null, null, null),
  (509, 'DISPLAY JERKY 5 PC 0.8OZ', 'AFFP0112', 119, 360, 9, 5, null),
  (508, 'DISPLAY SOLELY GUMMIES 10 PC', 'AFFP0111', 119, 260, 6, 6, null),
  (510, 'DISPLAY VARIETY PACK ND 2024', 'AFFP0113', 119, 440, 6, 6, null),
  (479, 'FRUIT JERKY 368GR', 'AFFP0083', 119, 60, 9, 5, null),
  (498, 'INSERTO SOLELY FRUITJERKY 24CT BOX MANGO', 'AFFP0102', 119, 80, 5, 6, null),
  (497, 'SOLELY FRUITJERKY 24CT BOX MANGO', 'AFFP0101', 119, 140, 6, 3, null),
  (438, 'CAJILLA_IND_ABK_60ML', 'AFFP0043', 106, 1300, 6, 5, null),
  (439, 'CAJILLA_IND_AD_FERALESS_75ML', 'AFFP0044', 106, 600, 6, 5, null),
  (456, 'CAJILLA_IND_VAINILLA_ROSE', 'AFFP0061', 106, 1, 6, 5, null),
  (471, 'CAJILLA_SALVAGGIO_HUMAN_50ML', 'AFFP0075', 106, 1, 8, 4, null),
  (455, 'CAJILLAS COMBAT (AMBOS CAMBIOS)', 'AFFP0060', 106, 1350, 8, 4, null),
  (489, 'CJ_IND_NIGHT_GLOW_V2', 'AFFP0093', 106, 1100, 6, 5, null),
  (457, 'CHOCOLITOS 12 PACK', 'AFFP0062', 113, 300, 8, 4, null),
  (525, 'BFA4 CERRADA JUEGO DE V PRISMA 490ML', 'AFFP0129', 126, 65, 6, 3, null),
  (524, 'KS6 SOAVE 25 GENERICO LINNERBLANCO', 'AFFP0128', 126, 78, 6, 3, null),
  (437, 'ESTUCHES A Y B', 'AFFP0042', 98, 171, 9, 17, null),
  (411, 'FAJILLA', 'AFFP0016', 98, 1100, 9, 5, null),
  (474, 'MORADO GRAND MAYAN', 'AFFP0078', 118, 100, 4, 4, null),
  (469, 'CAJILLA CONSOME 24 PZAS.', 'AFFP0073', 116, 1300, 6, 5, null),
  (468, 'CAJILLA CONSOME 8PZAS.', 'AFFP0072', 116, 2300, 9, 5, null),
  (470, 'CAJILLA_CONSOME_12PACK', 'AFFP0074', 116, 1700, 9, 7, null),
  (461, 'CAJILLA_CONSOME_12PACK', 'AFFP0066', 116, 1700, 9, 7, null),
  (467, 'CHAROLA BEEF FLAVORED', 'AFFP0071', 116, 150, 3, 6, null),
  (578, '6 PACK SALAVERRIA', 'AFFP0184', 136, 80, 6, 3, null),
  (577, 'SEPARADOR_CHICO_SALAVERRIA', 'AFFP0183', 136, 930, 9, 5, null),
  (576, 'SEPARADOR_GRANDE_SALAVERRIA', 'AFFP0182', 136, 620, 9, 5, null),
  (412, 'PULLED_CHICKEN', 'AFFP0017', 99, 500, 9, 5, null),
  (419, 'DISPLAY_AGUAS_FRESCAS12', 'AFFP0025', 102, 800, 8, 4, null),
  (543, 'DISPLAY BARRA ADHESIVA KORES 20 G', 'AFFP0147', 130, 360, 8, 4, null),
  (542, 'DISPLAY BARRA ADHESIVA KORES 40 G', 'AFFP0146', 130, 475, 6, 5, null),
  (541, 'DISPLAY BARRA ADHESIVA KORES 8 G', 'AFFP0145', 130, 500, 9, 5, null),
  (503, 'INSERTO CHICO - PACK DE NEBBIOLO Y PETITE SIRAH (+2VASOS)', 'AFFP0106', 124, 252, 9, 5, null),
  (504, 'INSERTO GRANDE - PACK DE NEBBIOLO Y PETITE SIRAH (+2VASOS)', 'AFFP0107', 124, 400, 5, 5, null),
  (501, 'PACK DE NEBBIOLO Y PETITE SIRAH (+2VASOS) - CAJA', 'AFFP0105', 124, 65, 6, 3, null),
  (579, '3TQIT504 CJ CAPLE ITALP GRMET LASAGNA FESTONATA CN MICA 500G', 'AFFP0185', 108, 338, 6, 5, null),
  (499, 'CAJA LASAGNE FESTONATA 500 GR ESTUCHADORA', 'AFFP0103', 108, 275, 6, 5, null),
  (442, 'CAJA_SURTIDO_NAVIDEÑO_450', 'AFFP0047', 108, 160, 5, 5, null),
  (488, 'LASAGE_FESTONATA_500G', 'AFFP0092', 108, 375, 5, 5, null),
  (535, 'LASAGNE TRADICIONAL 500 G', 'AFFP0139', 108, 625, 5, 5, null),
  (590, 'RON BLANCO ANTILLANO', null, 138, null, null, null, null),
  (591, 'VUIDA ROMERO MAS 2 SHOTS 275 ML', null, 138, null, null, null, null),
  (555, 'CROCANTE DE ALMENDRA BAÑADO EN CHOCOLATE', 'AFFP0161', 132, 600, 8, 4, null),
  (561, 'DISPLAY SERRALPINA', 'AFFP0167', 134, 156, 5, 6, null),
  (447, 'MANTEQUILLA_12PACK', 'AFFP0052', 110, 350, 9, 5, null),
  (466, 'CAJA_QUESO_CREMA_1.36KG', 'AFFP0070', 115, 260, 6, 5, null),
  (460, 'LALA MANTEQUILLA 4 PACK', 'AFFP0065', 115, 1850, 8, 4, null),
  (453, 'LIGAS_LEON_100G', 'AFFP0058', 112, 700, 8, 4, null),
  (462, '6PACK WISKY 200', 'AFFP0067', 109, 40, 9, 5, null),
  (448, 'CAJA_DUO_PACK_ZAVERICH (TODAS SUS PRESENTACIONES)', 'AFFP0053', 109, 90, 6, 3, null),
  (446, 'CAJA_WISKY_MALTA', 'AFFP0051', 109, 200, 6, 5, null),
  (570, 'COLLARIN EXTENDIDO PARA BOTELLA', 'AFFP0176', 109, 880, 20, 8, null),
  (568, 'ESTUCHE DE CAJA MUNDIAL', 'AFFP0174', 109, 30, 8, 4, null),
  (454, 'ESTUCHE MEZCAL ARMELLAN', 'AFFP0059', 109, 250, 5, 6, null),
  (452, 'ESTUCHE_MC_ANDREWS_GREEN_APPLE', 'AFFP0057', 109, 200, 6, 5, null),
  (445, 'INSERTO_WISKY_MALTA', 'AFFP0050', 109, 2100, 6, 4, null),
  (491, 'PETER WALACE', 'AFFP0095', 109, 275, 6, 5, null),
  (572, 'PLANO FAMILIA 1', 'AFFP0178', 135, 288, 6, 5, null),
  (573, 'PLANO FAMILIA 2', 'AFFP0179', 135, 322, 9, 5, null),
  (571, 'PLANO MACMA 150 G', 'AFFP0177', 135, 440, 6, 5, null),
  (532, 'S-051 MEDIBUTIN', 'AFFP0136', 127, 120, 20, 8, null),
  (533, 'S-052 , S-007 (MEDIBUTIN CAJA Y CRONOCAPS 3Y5 MG)', 'AFFP0137', 127, 1248, 6, 5, null),
  (414, '4 PACK_LIME', 'AFFP0019', 100, 180, 9, 4, null),
  (544, '6 PACK DUVEL', 'AFFP0148', 100, 80, 6, 3, null),
  (413, '8PACK_VARIETY', 'AFFP0018', 100, 200, 8, 4, null),
  (424, 'CAJA EUROPA', 'AFFP0029', 100, 60, 4, 3, null),
  (487, 'CAJA OKTOBERFEST INSERTO 1', 'AFFP0091', 100, 261, 5, 5, null),
  (485, 'CAJA OKTOBERFEST INSERTO 2', 'AFFP0089', 100, 198, 9, 5, null),
  (486, 'CAJA OKTOBERFEST INSERTO 3', 'AFFP0090', 100, 218, 8, 4, null),
  (484, 'CAJA OKTOBERFEST PACK', 'AFFP0088', 100, 36, 4, 3, null),
  (480, 'CAJA OKTOBERTFEST PACK + TARRO', 'AFFP0084', 100, 310, 2, 8, null),
  (582, 'INSERTO DUVEL 750 ML + COPA', 'AFFP0188', 100, 234, 9, 5, null),
  (583, 'INSERTO DUVEL 750 ML + COPA', 'AFFP0189', 100, 1125, 5, 6, null),
  (584, 'INSERTO DUVEL 750 ML + COPA', 'AFFP0190', 100, 638, 6, 6, null),
  (585, 'INSERTO DUVEL 750 ML + COPA', 'AFFP0191', 100, 238, 9, 5, null),
  (586, 'INSERTO DUVEL 750 ML + COPA', 'AFFP0192', 100, 764, 5, 6, null),
  (587, 'INSERTO DUVEL 750 ML + COPA', 'AFFP0193', 100, 510, 5, 6, null),
  (545, 'INSERTOS 6 PACK DUVEL', 'AFFP0149', 100, 480, 5, 6, null),
  (425, 'SEPARADOR CHICO CAJA EUROPA', 'AFFP0030', 100, 86, 20, 8, null),
  (426, 'SEPARADOR_GRANDE_CAJA_EUROPA', 'AFFP0031', 100, 286, 9, 5, null),
  (435, 'CAJA CONOS 104 (CAPLE CHILENO 14 PTS)', 'AFFP0040', 105, 350, 9, 5, null),
  (434, 'CAJA_CONOS_106', 'AFFP0039', 105, 375, 5, 4, null),
  (433, 'CAJA_CONOS_108', 'AFFP0038', 105, 375, 5, 4, null),
  (422, 'BANCO MATERDEI', 'AFFP0028', 94, 1425, 9, 5, null),
  (423, 'BANCO MATERDEI (CALIBRE 20 PTS)', 'AFFP0028', 94, 1600, 9, 5, null),
  (421, 'CAJA MATERDEI', 'AFFP0027', 94, 400, 9, 4, null),
  (450, 'CAJA_SWEENY_ 54S (AMBOS ARTES)', 'AFFP0055', 94, 840, 5, 6, null),
  (444, 'CJ_GOODWILL_ESPECIAS (TODAS LAS PRESENTACIONES)', 'AFFP0049', 94, 1950, 9, 5, null),
  (400, 'DOBLETT_16 (TODOS LOS CAMBIOS)', 'AFFP0005', 94, 750, 9, 5, null),
  (407, 'DOBLETT_2PACK', 'AFFP0012', 94, 300, 9, 5, null),
  (449, 'ENDULZANTE_SELECTO_SUCRALOSA_200', 'AFFP0054', 94, 475, 5, 6, null),
  (420, 'EXHIBIDOR ATOLE SELECTO', 'AFFP0026', 94, 510, 9, 4, null),
  (410, 'REMEDY (TODOS LOS CAMBIOS)', 'AFFP0015', 94, 750, 9, 5, null),
  (408, 'SUPERPACK', 'AFFP0013', 94, 200, 5, 6, null),
  (483, 'CAJA_PARA_CELULAR_OK', 'AFFP0087', 103, 70, 6, 3, null),
  (427, 'ESTUCHE INDIVIDUAL SUSHI', 'AFFP0032', 103, 105, 6, 3, null),
  (428, 'ESTUCHE PACK SUSHI', 'AFFP0033', 103, 22, 4, 3, null),
  (418, 'AMARANTO_ARANDANO100/ AMARANTO_CHISPAS100', 'AFFP0024', 101, 400, 9, 5, null),
  (417, 'AMARANTO_ARANDANO190/ AMARANTO_CHISPAS190', 'AFFP0023', 101, 250, 9, 5, null),
  (482, 'AVENA CON NUEZ PREMIUM', 'AFFP0086', 101, 90, 6, 3, null),
  (441, 'AVENA NUEZ 1KG', 'AFFP0046', 101, 90, 6, 3, null),
  (436, 'CAJA GV BARRAS (TODOS LOS CAMBIOS)', 'AFFP0041', 101, 450, 9, 5, null),
  (459, 'CAJA_SALVADO_12', 'AFFP0064', 101, 70, 6, 3, null),
  (515, 'CHAROLA MANTEQUILLA PREMIUM', 'AFFP0118', 101, null, null, null, null),
  (465, 'CJ PANECILLO DE SALVADO 1.2 KG', 'AFFP0069', 101, 40, 6, 3, null),
  (451, 'TEQUILERA_HACIENDA_DE_TEPA_700ML', 'AFFP0056', 111, 180, 6, 5, null),
  (567, 'CHAROLA GRANDE TORI TORI', 'AFFP0173', 131, null, null, null, null),
  (546, 'FAJILLA 1 NIVEL', 'AFFP0152', 131, 460, 9, 5, null),
  (547, 'FAJILLA 2 NIVELES', 'AFFP0153', 131, 391, 9, 5, null),
  (548, 'FAJILLA 3 NIVELES', 'AFFP0154', 131, 380, 8, 4, null),
  (566, 'FAJILLA CHAROLA GRANDE TORI TORI', 'AFFP0172', 131, 240, 6, 3, null),
  (549, 'FAJILLA PARA PROYECTO SUSHI', 'AFFP0155', 131, null, null, null, null),
  (563, 'INSERTO CON AGUJEROS CHAROLA GRANDE TORI TORI', 'AFFP0169', 131, 952, 6, 3, null),
  (562, 'INSERTO DIVISOR CHAROLA TORI TORI GRANDE', 'AFFP0168', 131, 624, 5, 6, null),
  (564, 'INSRTO PALILLOS CHAROLA GRANDE TORI TORI', 'AFFP0170', 131, 632, 9, 5, null),
  (395, 'CAJA CONOS 104', 'AFFP0001', 93, 500, 9, 5, null),
  (397, 'CAJA CONOS 106', 'AFFP0002', 93, 600, 6, 4, null),
  (481, 'CAJA CONOS 106 V2', 'AFFP0085', 93, 250, 6, 5, null),
  (443, 'CAJA CONOS KOTTLER', 'AFFP0048', 93, 500, 9, 5, null),
  (399, 'CAJA CONOS REBORDE 42 BR', 'AFFP0004', 93, 600, 6, 3, null),
  (396, 'CAJA CONOS SUPREME', 'AFFP0001', 93, 500, 9, 5, null),
  (398, 'CAJA_CONOS_108', 'AFFP0003', 93, 250, 6, 5, null),
  (511, 'CONOS VITRALITO X5', 'AFFP0114', 96, 2200, 20, 8, null),
  (406, 'VITRALITO_FORROX4', 'AFFP0011', 96, 2400, 20, 8, null),
  (405, 'VITRALITOX4', 'AFFP0010', 96, 200, 6, 4, null),
  (429, 'INSERTO DE ZAPATO BABY', 'AFFP0034', 104, 1300, 20, 8, null),
  (432, 'INSERTO DE ZAPATO CABALLERO', 'AFFP0037', 104, 3, 9, 4, null),
  (431, 'INSERTO DE ZAPATO DAMA', 'AFFP0036', 104, 4100, 9, 4, null),
  (430, 'INSERTO DE ZAPATOS JUNIOR', 'AFFP0035', 104, 4100, 9, 5, null);

insert into trucks (id, name, pallet_capacity, freight_category) values
  (3, 'Torton chico', 12, 'torton'),
  (2, 'Torton grande', 14, 'torton'),
  (1, 'Trailer', 26, 'trailer');

insert into destinations (id, name, cost_trailer, cost_torton, cost_camion_35, cost_reparto) values
  (1, 'Arandas Jalisco', 25000, 22000, 17500, 500),
  (3, 'Celaya', 16000, 14500, 12000, null),
  (9, 'Ecatepec', 5500, 4500, 3200, null),
  (10, 'Local', 5500, 4500, 3200, null),
  (11, 'Local+', 5800, 4700, 4000, null),
  (7, 'Ojinaga', 60000, 54000, 46000, null),
  (5, 'Orizaba', 24500, 16000, 12000, null),
  (6, 'Puebla', 15000, 12000, 10200, null),
  (4, 'San Juan del Río', 13000, 10000, 8000, null),
  (8, 'San Luis Potosí', 21000, 18000, 14000, null),
  (2, 'Zapopan', 25000, 22000, 17500, null);

-- los ids se insertaron a mano: adelanta los contadores para que los nuevos no choquen
select setval(pg_get_serial_sequence('clients','id'),      (select max(id) from clients));
select setval(pg_get_serial_sequence('products','id'),     (select max(id) from products));
select setval(pg_get_serial_sequence('trucks','id'),       (select max(id) from trucks));
select setval(pg_get_serial_sequence('destinations','id'), (select max(id) from destinations));

-- ===== permisos =====
-- La app no tiene login, así que entra con la llave anon (que es pública porque
-- viaja en el HTML). Estas políticas le dan lectura y escritura completas.
-- IMPORTANTE: cualquiera que tenga la URL de la app puede leer y escribir estos
-- datos. Si eso no es aceptable, hay que agregar login de Supabase y cambiar
-- 'anon' por 'authenticated' en las políticas de abajo.
alter table clients      enable row level security;
alter table products     enable row level security;
alter table trucks       enable row level security;
alter table destinations enable row level security;
alter table truck_loads  enable row level security;

create policy anon_all on clients      for all to anon using (true) with check (true);
create policy anon_all on products     for all to anon using (true) with check (true);
create policy anon_all on trucks       for all to anon using (true) with check (true);
create policy anon_all on destinations for all to anon using (true) with check (true);
create policy anon_all on truck_loads  for all to anon using (true) with check (true);
